#pragma once 

module geometry_msgs {
  module msg {
    @verbatim (language="comment", text=
      " This contains the position of a point in free space")
    struct Point {
      double x;

      double y;

      double z;
    };
  };
};
