module geometry_msgs {
  module msg {
    @verbatim (language="comment", text=
      " This represents an orientation in free space in quaternion form.")
    struct Quaternion {
      double x;
      double y;
      double z;
      double w;
    };
  };
};
