#pragma once 

#include "Header.idl"
#include "DirectServo.idl"
#include "SmartServo.idl"
#include "SmartServoLin.idl"

module sunrisedds_interfaces {
  module msg {
    module ServoCommand_Constants {
      const uint8 SMART_SERVO = 0;
      const uint8 DIRECT_SERVO = 1;
      const uint8 SMART_SERVO_LIN = 2;
    };
    struct ServoCommand {
      std_msgs::msg::Header header;

      uint8 type;

      sunrisedds_interfaces::msg::SmartServo smart_servo;

      sunrisedds_interfaces::msg::DirectServo direct_servo;

      sunrisedds_interfaces::msg::SmartServoLin smart_servo_lin;
    };
  };
};
