#pragma once

#include "Pose.idl"
#include "Vector3.idl"

module sunrisedds_interfaces {
  module msg {
    module SmartServoLin_Constants {
      const uint8 SMART_SERVO_LIN_CARTESIAN_POSE = 0;
      const uint8 SMART_SERVO_LIN_CARTESIAN_POSE_VELOCITY = 1;
    };
    struct SmartServoLin {
      uint8 type;

      geometry_msgs::msg::Pose cartesian_pose;

      geometry_msgs::msg::Vector3 translational_velocity;
    };
  };
};
