/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: DirectServo.h
  Source: DirectServo.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_DIRECTSERVO_H
#define DDSC_DIRECTSERVO_H

#include "Pose.h"

#include "JointQuantity.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sunrisedds_interfaces_msg_DirectServo_Constants_DIRECT_SERVO_JOINT_POSITION 0
#define sunrisedds_interfaces_msg_DirectServo_Constants_DIRECT_SERVO_CARTESIAN_POSE 1
typedef struct sunrisedds_interfaces_msg_DirectServo
{
  uint8_t type;
  sunrisedds_interfaces_msg_JointQuantity joint_position;
  geometry_msgs_msg_Pose cartesian_pose;
  sunrisedds_interfaces_msg_JointQuantity joint_velocity_rel;
} sunrisedds_interfaces_msg_DirectServo;

extern const dds_topic_descriptor_t sunrisedds_interfaces_msg_DirectServo_desc;

#define sunrisedds_interfaces_msg_DirectServo__alloc() \
((sunrisedds_interfaces_msg_DirectServo*) dds_alloc (sizeof (sunrisedds_interfaces_msg_DirectServo)));

#define sunrisedds_interfaces_msg_DirectServo_free(d,o) \
dds_sample_free ((d), &sunrisedds_interfaces_msg_DirectServo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DIRECTSERVO_H */
