/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: JointQuantity.c
  Source: JointQuantity.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "JointQuantity.h"

static const uint32_t sunrisedds_interfaces_msg_JointQuantity_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a1),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a2),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a3),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a4),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a5),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a6),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_JointQuantity, a7),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sunrisedds_interfaces_msg_JointQuantity_desc =
{
  sizeof (sunrisedds_interfaces_msg_JointQuantity),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "sunrisedds_interfaces::msg::dds_::JointQuantity_",
  NULL,
  8,
  sunrisedds_interfaces_msg_JointQuantity_ops,
  ""
};
