/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: JointState.c
  Source: JointState.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "JointState.h"

static const uint32_t sensor_msgs_msg_JointState_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (sensor_msgs_msg_JointState, header.stamp.sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_JointState, header.stamp.nanosec),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_JointState, header.frame_id),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STR, offsetof (sensor_msgs_msg_JointState, name),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_JointState, position),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_JointState, velocity),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_JointState, effort),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_JointState_desc =
{
  sizeof (sensor_msgs_msg_JointState),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "sensor_msgs::msg::dds_::JointState_",
  NULL,
  8,
  sensor_msgs_msg_JointState_ops,
  ""
};
