/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: JointQuantity.h
  Source: JointQuantity.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_JOINTQUANTITY_H
#define DDSC_JOINTQUANTITY_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sunrisedds_interfaces_msg_JointQuantity
{
  double a1;
  double a2;
  double a3;
  double a4;
  double a5;
  double a6;
  double a7;
} sunrisedds_interfaces_msg_JointQuantity;

extern const dds_topic_descriptor_t sunrisedds_interfaces_msg_JointQuantity_desc;

#define sunrisedds_interfaces_msg_JointQuantity__alloc() \
((sunrisedds_interfaces_msg_JointQuantity*) dds_alloc (sizeof (sunrisedds_interfaces_msg_JointQuantity)));

#define sunrisedds_interfaces_msg_JointQuantity_free(d,o) \
dds_sample_free ((d), &sunrisedds_interfaces_msg_JointQuantity_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_JOINTQUANTITY_H */
