/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_mtp_ra_sunrisedds_msg_JointPosition */

#ifndef _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
#define _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
 * Method:    getFromJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition_getFromJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
 * Method:    getToJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition_getToJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
 * Method:    getTopicDescriptor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition_getTopicDescriptor
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointPosition
 * Method:    getDestructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointPosition_getDestructor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
