/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_mtp_ra_sunrisedds_msg_Time */

#ifndef _Included_no_ntnu_mtp_ra_sunrisedds_msg_Time
#define _Included_no_ntnu_mtp_ra_sunrisedds_msg_Time
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_Time
 * Method:    getFromJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_Time_getFromJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_Time
 * Method:    getToJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_Time_getToJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_Time
 * Method:    getTopicDescriptor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_Time_getTopicDescriptor
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_Time
 * Method:    getDestructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_Time_getDestructor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
