/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_mtp_ra_sunrisedds_msg_JointState */

#ifndef _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointState
#define _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointState
 * Method:    getDestructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointState_getDestructor
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointState
 * Method:    getFromJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointState_getFromJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointState
 * Method:    getToJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointState_getToJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointState
 * Method:    getTopicDescriptor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointState_getTopicDescriptor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
