/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_mtp_ra_sunrisedds_SunriseDDS */

#ifndef _Included_no_ntnu_mtp_ra_sunrisedds_SunriseDDS
#define _Included_no_ntnu_mtp_ra_sunrisedds_SunriseDDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_SunriseDDS
 * Method:    nativeCreateDomainParticipant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_ntnu_mtp_ra_sunrisedds_SunriseDDS_nativeCreateDomainParticipant
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
