/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity */

#ifndef _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
#define _Included_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
 * Method:    getFromJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity_getFromJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
 * Method:    getToJavaConverter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity_getToJavaConverter
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
 * Method:    getTopicDescriptor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity_getTopicDescriptor
  (JNIEnv *, jclass);

/*
 * Class:     no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity
 * Method:    getDestructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_ntnu_mtp_ra_sunrisedds_msg_JointQuantity_getDestructor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
