/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_Topic */

#ifndef _Included_org_sunrisedds_sunrisedds_Topic
#define _Included_org_sunrisedds_sunrisedds_Topic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_Topic
 * Method:    nativeCreateTopicHandle
 * Signature: (ILjava/lang/Class;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_Topic_nativeCreateTopicHandle
  (JNIEnv *, jclass, jint, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
