/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_Simple */

#ifndef _Included_org_sunrisedds_sunrisedds_Simple
#define _Included_org_sunrisedds_sunrisedds_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_Simple
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_Simple_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
