/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_DomainParticipant */

#ifndef _Included_org_sunrisedds_sunrisedds_DomainParticipant
#define _Included_org_sunrisedds_sunrisedds_DomainParticipant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_DomainParticipant
 * Method:    nativeCreateDomainParticipant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_DomainParticipant_nativeCreateDomainParticipant
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
