/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_SunriseDDS */

#ifndef _Included_org_sunrisedds_sunrisedds_SunriseDDS
#define _Included_org_sunrisedds_sunrisedds_SunriseDDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_SunriseDDS
 * Method:    nativeCreateDomainParticipant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_SunriseDDS_nativeCreateDomainParticipant
  (JNIEnv *, jclass);

/*
 * Class:     org_sunrisedds_sunrisedds_SunriseDDS
 * Method:    nativeCreateSubscriber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_SunriseDDS_nativeCreateSubscriber
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_sunrisedds_sunrisedds_SunriseDDS
 * Method:    nativeCreateJointPositionReader
 * Signature: (IILjava/lang/String;Lorg/sunrisedds/sunrisedds/OnDataAvailableCallbackInterface;)I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_SunriseDDS_nativeCreateJointPositionReader
  (JNIEnv *, jclass, jint, jint, jstring, jobject);

/*
 * Class:     org_sunrisedds_sunrisedds_SunriseDDS
 * Method:    nativeJointPositionReaderRead
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_sunrisedds_sunrisedds_SunriseDDS_nativeJointPositionReaderRead
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
