/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_Publisher */

#ifndef _Included_org_sunrisedds_sunrisedds_Publisher
#define _Included_org_sunrisedds_sunrisedds_Publisher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_Publisher
 * Method:    nativeCreatePublisherHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_Publisher_nativeCreatePublisherHandle
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
