/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sunrisedds_sunrisedds_DataWriter */

#ifndef _Included_org_sunrisedds_sunrisedds_DataWriter
#define _Included_org_sunrisedds_sunrisedds_DataWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sunrisedds_sunrisedds_DataWriter
 * Method:    nativeCreateDataWriterHandle
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_sunrisedds_sunrisedds_DataWriter_nativeCreateDataWriterHandle
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
