/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Point.c
  Source: Point.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "Point.h"

static const uint32_t geometry_msgs_msg_Point_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Point_desc =
{
  sizeof (geometry_msgs_msg_Point),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "geometry_msgs::msg::dds_::Point_",
  NULL,
  4,
  geometry_msgs_msg_Point_ops,
  ""
};
