/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Pose.h
  Source: Pose.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_POSE_H
#define DDSC_POSE_H

#include "Point.h"

#include "Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Pose
{
  geometry_msgs_msg_Point position;
  geometry_msgs_msg_Quaternion orientation;
} geometry_msgs_msg_Pose;

extern const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc;

#define geometry_msgs_msg_Pose__alloc() \
((geometry_msgs_msg_Pose*) dds_alloc (sizeof (geometry_msgs_msg_Pose)));

#define geometry_msgs_msg_Pose_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Pose_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_POSE_H */
