/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Pose.c
  Source: Pose.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "Pose.h"

static const uint32_t geometry_msgs_msg_Pose_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, position.x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, position.y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, position.z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, orientation.x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, orientation.y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, orientation.z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose, orientation.w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc =
{
  sizeof (geometry_msgs_msg_Pose),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "geometry_msgs::msg::dds_::Pose_",
  NULL,
  8,
  geometry_msgs_msg_Pose_ops,
  ""
};
