/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Quaternion.c
  Source: Quaternion.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "Quaternion.h"

static const uint32_t geometry_msgs_msg_Quaternion_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Quaternion_desc =
{
  sizeof (geometry_msgs_msg_Quaternion),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "geometry_msgs::msg::dds_::Quaternion_",
  NULL,
  5,
  geometry_msgs_msg_Quaternion_ops,
  ""
};
