/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: SmartServo.h
  Source: SmartServo.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_SMARTSERVO_H
#define DDSC_SMARTSERVO_H

#include "Pose.h"

#include "JointQuantity.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sunrisedds_interfaces_msg_SmartServo_Constants_SMART_SERVO_JOINT_POSITION 0
#define sunrisedds_interfaces_msg_SmartServo_Constants_SMART_SERVO_JOINT_POSITION_VELOCITY 1
#define sunrisedds_interfaces_msg_SmartServo_Constants_SMART_SERVO_CARTESIAN_POSE 2
typedef struct sunrisedds_interfaces_msg_SmartServo
{
  uint8_t type;
  sunrisedds_interfaces_msg_JointQuantity joint_position;
  sunrisedds_interfaces_msg_JointQuantity joint_velocity;
  geometry_msgs_msg_Pose cartesian_pose;
  sunrisedds_interfaces_msg_JointQuantity joint_velocity_rel;
  sunrisedds_interfaces_msg_JointQuantity joint_acceleration_rel;
} sunrisedds_interfaces_msg_SmartServo;

extern const dds_topic_descriptor_t sunrisedds_interfaces_msg_SmartServo_desc;

#define sunrisedds_interfaces_msg_SmartServo__alloc() \
((sunrisedds_interfaces_msg_SmartServo*) dds_alloc (sizeof (sunrisedds_interfaces_msg_SmartServo)));

#define sunrisedds_interfaces_msg_SmartServo_free(d,o) \
dds_sample_free ((d), &sunrisedds_interfaces_msg_SmartServo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SMARTSERVO_H */
