/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: SmartServoLin.h
  Source: SmartServoLin.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_SMARTSERVOLIN_H
#define DDSC_SMARTSERVOLIN_H

#include "Pose.h"

#include "Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sunrisedds_interfaces_msg_SmartServoLin_Constants_SMART_SERVO_LIN_CARTESIAN_POSE 0
#define sunrisedds_interfaces_msg_SmartServoLin_Constants_SMART_SERVO_LIN_CARTESIAN_POSE_VELOCITY 1
typedef struct sunrisedds_interfaces_msg_SmartServoLin
{
  uint8_t type;
  geometry_msgs_msg_Pose cartesian_pose;
  geometry_msgs_msg_Vector3 translational_velocity;
} sunrisedds_interfaces_msg_SmartServoLin;

extern const dds_topic_descriptor_t sunrisedds_interfaces_msg_SmartServoLin_desc;

#define sunrisedds_interfaces_msg_SmartServoLin__alloc() \
((sunrisedds_interfaces_msg_SmartServoLin*) dds_alloc (sizeof (sunrisedds_interfaces_msg_SmartServoLin)));

#define sunrisedds_interfaces_msg_SmartServoLin_free(d,o) \
dds_sample_free ((d), &sunrisedds_interfaces_msg_SmartServoLin_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SMARTSERVOLIN_H */
