/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: SmartServoLin.c
  Source: SmartServoLin.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "SmartServoLin.h"

static const uint32_t sunrisedds_interfaces_msg_SmartServoLin_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sunrisedds_interfaces_msg_SmartServoLin, type),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.position.x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.position.y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.position.z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.orientation.x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.orientation.y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.orientation.z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, cartesian_pose.orientation.w),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, translational_velocity.x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, translational_velocity.y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sunrisedds_interfaces_msg_SmartServoLin, translational_velocity.z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sunrisedds_interfaces_msg_SmartServoLin_desc =
{
  sizeof (sunrisedds_interfaces_msg_SmartServoLin),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "sunrisedds_interfaces::msg::dds_::SmartServoLin_",
  NULL,
  12,
  sunrisedds_interfaces_msg_SmartServoLin_ops,
  ""
};
