/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Time.c
  Source: Time.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "Time.h"

static const uint32_t builtin_interfaces_msg_Time_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t builtin_interfaces_msg_Time_desc =
{
  sizeof (builtin_interfaces_msg_Time),
  4u,
  0u,
  0u,
  "builtin_interfaces::msg::dds_::Time_",
  NULL,
  3,
  builtin_interfaces_msg_Time_ops,
  ""
};
