/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Vector3.h
  Source: Vector3.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_VECTOR3_H
#define DDSC_VECTOR3_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Vector3
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_Vector3;

extern const dds_topic_descriptor_t geometry_msgs_msg_Vector3_desc;

#define geometry_msgs_msg_Vector3__alloc() \
((geometry_msgs_msg_Vector3*) dds_alloc (sizeof (geometry_msgs_msg_Vector3)));

#define geometry_msgs_msg_Vector3_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Vector3_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VECTOR3_H */
