/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Vector3.c
  Source: Vector3.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "Vector3.h"

static const uint32_t geometry_msgs_msg_Vector3_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Vector3_desc =
{
  sizeof (geometry_msgs_msg_Vector3),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "geometry_msgs::msg::dds_::Vector3_",
  NULL,
  4,
  geometry_msgs_msg_Vector3_ops,
  ""
};
